"""终端 UI 的公开导出。"""

from __future__ import annotations

from ._capabilities import TerminalCapabilities, detect_capabilities
from . import _capabilities as _capabilities
from ._colors import (
    AI_PREFIX,
    USER_PREFIX,
    ANSI_BOLD,
    ANSI_BRIGHT_BLACK,
    ANSI_BRIGHT_BLUE,
    ANSI_BRIGHT_CYAN,
    ANSI_BRIGHT_GREEN,
    ANSI_BRIGHT_MAGENTA,
    ANSI_BRIGHT_RED,
    ANSI_BRIGHT_WHITE,
    ANSI_BRIGHT_YELLOW,
    ANSI_CLEAR_LINE,
    ANSI_CLEAR_TO_LINE_END,
    ANSI_DIM,
    ANSI_ERASE_TO_END,
    ANSI_ITALIC,
    ANSI_PREVIOUS_LINE,
    ANSI_RESET,
    ANSI_RESTORE_CURSOR,
    ANSI_SAVE_CURSOR,
    ANSI_UNDERLINE,
    COLOR_ACCENT,
    COLOR_ERROR,
    COLOR_HEADING,
    COLOR_MUTED,
    COLOR_PRIMARY,
    COLOR_SECONDARY,
    COLOR_SUCCESS,
    COLOR_TEXT,
    COLOR_WARNING,
    color_text,
    get_color_sequence,
    strip_ansi,
)
from ._core import TerminalUI
from ._display import (
    _char_display_width,
    _combine_surrogate_pair,
    _contains_complex_display_width,
    _delete_last_display_unit,
    _dialog_continuation_prefix,
    _display_width,
    _ellipsize_display_text,
    _iter_display_units,
    _normalize_terminal_text,
    _preview_display_rows,
    _split_display_rows,
    _take_display_width,
)
from ._markdown import MarkdownSpan, MarkdownStreamState
from ._spinner import InputBar, SPINNER_FRAMES, WaitingIndicator
from ._status import StatusLine

__all__ = [
    "AI_PREFIX",
    "USER_PREFIX",
    "TerminalCapabilities",
    "TerminalUI",
    "InputBar",
    "StatusLine",
    "WaitingIndicator",
    "MarkdownSpan",
    "MarkdownStreamState",
    "SPINNER_FRAMES",
    "detect_capabilities",
    "color_text",
    "get_color_sequence",
    "strip_ansi",
    "ANSI_RESET",
    "ANSI_BOLD",
    "ANSI_DIM",
    "ANSI_ITALIC",
    "ANSI_UNDERLINE",
    "ANSI_CLEAR_LINE",
    "ANSI_CLEAR_TO_LINE_END",
    "ANSI_PREVIOUS_LINE",
    "ANSI_ERASE_TO_END",
    "ANSI_SAVE_CURSOR",
    "ANSI_RESTORE_CURSOR",
    "COLOR_PRIMARY",
    "COLOR_SECONDARY",
    "COLOR_SUCCESS",
    "COLOR_WARNING",
    "COLOR_ERROR",
    "COLOR_MUTED",
    "COLOR_TEXT",
    "COLOR_HEADING",
    "COLOR_ACCENT",
    "_char_display_width",
    "_combine_surrogate_pair",
    "_delete_last_display_unit",
    "_contains_complex_display_width",
    "_dialog_continuation_prefix",
    "_display_width",
    "_ellipsize_display_text",
    "_iter_display_units",
    "_normalize_terminal_text",
    "_preview_display_rows",
    "_split_display_rows",
    "_take_display_width",
]
