"""Agent 网关消息脱敏（可逆占位符 ｛Desensitized:n｝）。

模块划分：engine（匹配引擎）/ registry（序号注册表与周期）/ stream（事件流
还原）/ middleware（运行时装饰器与接线助手）/ oneshot（旁路一次性屏蔽还原）。
设计稿见 ``omnicrawl/docs/agent_gateway_desensitization_design.md``。
"""

from .engine import (
    MaskContext,
    SensitiveMatcher,
    find_entropy_spans,
    is_entropy_candidate,
    is_entropy_exempt,
    mask_structured_value,
    mask_text,
    shannon_entropy_bits,
)
from .gitleaks import GITLEAKS_SNAPSHOT_PATH, load_gitleaks_rules
from .middleware import DesensitizationError, DesensitizationRuntime, maybe_wrap_runtime
from .ner import (
    NER_ENTITY_TYPES,
    NerExtractor,
    NerLayer,
    NerModelError,
    build_ner_layer,
    clear_ner_cache,
    resolve_device,
    resolve_model_path,
)
from .oneshot import OneShotMasker, maybe_create_oneshot_masker
from .registry import (
    DesensitizationStats,
    PlaceholderCycle,
    SequenceRegistry,
    SessionSequenceCache,
    StableSequenceIndex,
    collect_placeholder_numbers,
    format_placeholder,
)
from .rules import (
    CATEGORY_BANK_CARD,
    CATEGORY_CONFIG_FLAGS,
    CATEGORY_DB_CONNECTION_STRING,
    CATEGORY_EMAIL,
    CATEGORY_EXTERNAL_IP,
    CATEGORY_GITLEAKS,
    CATEGORY_INTERNAL_IP,
    CATEGORY_LICENSE_PLATE,
    CATEGORY_MAC_ADDRESS,
    CATEGORY_PEM_PRIVATE_KEY,
    CATEGORY_URL,
    PatternRule,
    RuleLocality,
    RuleMatch,
    build_enabled_rules,
    builtin_rules,
    clear_scan_cache,
    is_external_ip,
    is_internal_ip,
    scan_cache_stats,
    scan_pattern_rules,
)
from .stream import StreamRestorer

__all__ = [
    "CATEGORY_BANK_CARD",
    "CATEGORY_CONFIG_FLAGS",
    "CATEGORY_DB_CONNECTION_STRING",
    "CATEGORY_EMAIL",
    "CATEGORY_EXTERNAL_IP",
    "CATEGORY_GITLEAKS",
    "CATEGORY_INTERNAL_IP",
    "CATEGORY_LICENSE_PLATE",
    "CATEGORY_MAC_ADDRESS",
    "CATEGORY_PEM_PRIVATE_KEY",
    "CATEGORY_URL",
    "DesensitizationError",
    "DesensitizationRuntime",
    "DesensitizationStats",
    "GITLEAKS_SNAPSHOT_PATH",
    "NER_ENTITY_TYPES",
    "MaskContext",
    "NerExtractor",
    "NerLayer",
    "NerModelError",
    "OneShotMasker",
    "PatternRule",
    "PlaceholderCycle",
    "RuleLocality",
    "RuleMatch",
    "SensitiveMatcher",
    "SequenceRegistry",
    "SessionSequenceCache",
    "StableSequenceIndex",
    "StreamRestorer",
    "build_enabled_rules",
    "build_ner_layer",
    "builtin_rules",
    "clear_ner_cache",
    "clear_scan_cache",
    "collect_placeholder_numbers",
    "resolve_device",
    "resolve_model_path",
    "find_entropy_spans",
    "format_placeholder",
    "is_entropy_candidate",
    "is_entropy_exempt",
    "is_external_ip",
    "is_internal_ip",
    "load_gitleaks_rules",
    "mask_structured_value",
    "mask_text",
    "maybe_create_oneshot_masker",
    "maybe_wrap_runtime",
    "scan_cache_stats",
    "scan_pattern_rules",
    "shannon_entropy_bits",
]
